### PR TITLE
chore: Android java snapshot release for forced decision

### PR DESCRIPTION
**Pull request by mnoman09**
## Summary
- Changed java version to BB-SNAPSHOT to add forced decision functionality

### CODE REVIEW

**Review by jaeopt — APPROVED** [review]
LGTM

**Review by msohailhussain — CHANGES_REQUESTED** [review]
add unit tests

**Review by jaeopt — APPROVED** [review]
LGTM

**Review by msohailhussain — APPROVED** [review]
lgtm

**Review by jaeopt — APPROVED** [review]
LGTM

**Pull request closed without merging**
