### PR TITLE
Bring back async init without the datafile.

### PR DESCRIPTION
**Pull request by mikeng13**

### CODE REVIEW

**Comment by tylerbrandt** [comment]
build

**Comment by mikeng13** [comment]
build

**Comment by tylerbrandt** [comment]
build

**Comment by tylerbrandt** [comment]
got through the build phase, but failed for browserstack credentials reasons https://jenkins.dz.optimizely.com/job/sdk-compatibility-android/29/console

**Comment by thomaszurkan-optimizely** [comment]
build

**Pull request merged**
