### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by elliotykim**

### CODE REVIEW

**Comment by elliotykim** [comment]
@optimizely/fullstack-devs 
@vraja2 
one last time for a clean commit history

**Comment by elliotykim** [comment]
Does that mean old files should still say 2016 even if they are modified? The logging changes in the other branch touches a large number of files @vraja2

**Comment by elliotykim** [comment]
@vraja2 could you take another look thanks!

**Comment by elliotykim** [comment]
@vraja2 do you know how to restart the test?

**Comment by vraja2** [comment]
just restarted it, you can do so through Travis

**Comment by vraja2** [comment]
@elliotykim make sure to squash and merge into devel

**Comment by elliotykim** [comment]
@vraja2 thanks for the reminder. waiting for travis

**Pull request merged**
