### PR TITLE
Change access modifiers so subclasses can access methods and members

### PR DESCRIPTION
**Pull request by elliotykim**
Without this change, it's a pain to extend `OptlyEventHandler`

https://optimizely.atlassian.net/browse/OASIS-809

@optimizely/fullstack-devs @vraja2

### CODE REVIEW

**Comment by elliotykim** [comment]
@vraja2 yeah implementing `EventHandler` is a possibility but I thought `OptlyEventHandler` was easier to use b/c it gives you logging already

Do you see any problems with making `OptlyEventHandler` extendable?

**Comment by elliotykim** [comment]
Continuing the thread in Jira:
https://optimizely.atlassian.net/browse/OASIS-809

**Comment by jophde** [comment]
The existing access modifiers are intentional. Users should implement
EventHandler and pass their instance to the Optimizely Manager builder.

On Jan 23, 2017 8:18 AM, "Elliot Kim" <notifications@github.com> wrote:

Continuing the thread in Jira:
https://optimizely.atlassian.net/browse/OASIS-809

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/optimizely/android-sdk/pull/80#issuecomment-274533866>,
or mute the thread

**Comment by elliotykim** [comment]
This PR was created to demonstrate one possible short-term solution for OASIS-809. It is no longer needed

**Pull request closed without merging**
