### PR TITLE
Remove activity files that do not do anything

### PR DESCRIPTION
**Pull request by elliotykim**
@optimizely/fullstack-devs 

@vraja2 do you know why these files exist? the test-app doesn't build with them there

### CODE REVIEW

**Comment by elliotykim** [comment]
@vraja2 I dunno why this doesn't build. tests all pass locally >.<

**Comment by vraja2** [comment]
@elliotykim it was added back in the copyright changes that were merged in earlier so that broke the test-app. Going to merge this change in to fix.

**Comment by vraja2** [comment]
actually, it looks like there are other unneeded files that were added as well. If you can take a second pass and ensure all these files are removed, we can merge in later, but I'm going to revert this for now.

**Comment by elliotykim** [comment]
Shoot, maybe I clicked "Update branch" and Github added those files. I'll fix this

**Comment by elliotykim** [comment]
Abandon this change and instead fix https://github.com/optimizely/android-sdk/commit/ae92208b0709b7a254f7d6102a44eccf0f376cba

**Comment by jophde** [comment]
These are used for .gradlew test-app:connectedAndroidTest which are our
MOST valuable tests. Please revert.

**Comment by elliotykim** [comment]
@jophde I don't think that's relevant anymore

**Comment by elliotykim** [comment]
actually the test is failing
@vraja2 does the test need to be rewritten for the updated test-app?
is the test automatically run somewhere?

**Comment by jophde** [comment]
The test automates the UI of those activities. They are relevant.

On Jan 23, 2017 8:43 AM, "Elliot Kim" <notifications@github.com> wrote:

actually the test is failing
@vraja2 <https://github.com/vraja2> does the test need to be rewritten for
the updated test-app?
is the test automatically run somewhere?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/optimizely/android-sdk/pull/79#issuecomment-274542388>,
or mute the thread

**Pull request closed without merging**
